spring:
  h2:
    console:
      enabled: true
      path: /h2-console # Đường dẫn truy cập vào H2 Console
  application:
    name: bookservice
  datasource:
    url: jdbc:h2:mem:bookDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
