spring:
  h2:
    console:
      enabled: true
      path: /h2-console # ???ng d?n truy c?p vào H2 Console
  application:
    name: employeeservice
  datasource:
    url: jdbc:h2:mem:employeeDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
axon:
  axonserver:
    client-id: employeeservice